version: "3"

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:usr/src/app:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] # updates in dev  
    env_file:
      - ./env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}  # to access env variables #{name_of_variable}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=#{SECRET_KEY}
      - ALGORITHM=#{ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=#{ACCESS_TOKEN_EXPIRE_MINUTES}    

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=#{DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    
volumes:
  postgres_db: